apiVersion: v1
kind: Service
metadata:
  name: loan-prediction-service
spec:
  type: LoadBalancer
  selector:
    app: loan-prediction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
